### ISSUE TITLE
Editing other ROMs

### ISSUE THREAD

**Issue by tattoo-girl** [laqieer/nightmare#4]
This seems like it edits ONLY  fire emblem: https://laqieer.github.io/nightmare

I have a gba ROM I'd like to delete or remove it's audio totally

Can I do it with this as I tried severally and nothing happened ..I had to get a GitHub acct to know what I'm doing wrong ? Why is it only fire emblem I see there? Perhaps a glitch ?

**Comment by laqieer** [comment]
It cannot edit other ROMs because no module. Provide modules and I will add them, then you can edit it.

**Comment by tattoo-girl** [comment]
Please explain module ? It's some fan-made Pokémon roms

I have mega power and unbound
roms

I wld like to remove the long opening scene story  (long ago king of kalos region etc. ) 

And also remove audio completely from both roms

Do you have another project similar to this :
https://www.pokecommunity.com/showthread.php?t=456210

https://pokewebkit.com

I tried that But it don't work either


I wonder if there's an online tool to upload & edit ROMs and download the result as a gba or zip file. All right there online as compared to downloading several tools.

**Comment by laqieer** [comment]
```
Nightmare is the tradition of Fire Emblem ROM hacking community.
A Nightmare module (.nmm file) is just a text file which defines structure in a data file.
New modules can also be created for any game.
```
Learn more [here](https://github.com/laqieer/Fire-Emblem-Nightmare-Modules)

**Comment by tattoo-girl** [comment]
Owww,  Ok that's pretty cool. I don't know where or how to get modules for mega-power & unbound.

But if you can,  it be nice if you would do a something for Pokemon

Or Better still a tool for all roms. consider,   ...consider the coconut 😝

I would be marking this issue as CLOSED then. since it's really not an issue with your tool/text-file. I would get an FE rom to to try this out on.
